---
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v3.0.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.14.0
  hooks:
    - id: yamllint
      files: \.(yaml|yml)$
      types: [file, yaml]
      language: python
      entry: yamllint -c .yamllint.yml
- repo: https://github.com/ansible/ansible-lint.git
  rev: v4.3.5
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
...
