---
plugins:
  - "@semantic-release/commit-analyzer"
  - - "@google/semantic-release-replace-plugin"
    - replacements:
      - files:
        - ronmallory/win_nuget/galaxy.yml
        from: "version: .*"
        to: "version: '${nextRelease.version}'"
        results:
        - file: ronmallory/win_nuget/galaxy.yml
          hasChanged: true
          numMatches: 1
          numReplacements: 1
        countMatches: true
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/git"
  - - "@semantic-release/git"
    - assets:
      - ronmallory/win_nuget/galaxy.yml
  - "@semantic-release/github"
  - "@semantic-release/changelog"
...
