---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    box: gusztavvargadr/windows-server-standard-core
    config_options:
      synced_folder: true
    memory: 4096
    cpus: 2
    provider_options:
      linked_clone: true
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--cpuexecutioncap', '90']"
    provision: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
