---
- name: Verify
  hosts: 127.0.0.1
  gather_facts: 'false'
  vars:
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_port: 55985
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_scheme: http
  tasks:
    - name: validate nuget command is avialable
      win_command: nuget
      changed_when: false
      register: results
...
