---
namespace: ronmallory
name: win_nuget
version: 1.0.1
readme: README.md
authors:
  - Ron Mallory Ronnymallory@gmail.com
description: |
  This collection installs and interacts with nuget.exe on a remote
  windows server.
license:
  - AGPL-3.0-or-later
license_file: LICENSE
tags:
  - windows
  - nuget
repository: https://github.com/RonMallory/win_nuget
documentation: https://github.com/RonMallory/win_nuget
homepage: https://github.com/RonMallory/win_nuget
issues: https://github.com/RonMallory/win_nuget/issues
...
