---
# actions to run on pull_request to publish to ansible-galaxy

name: publish

on:
  push:
    branches:
      - master
jobs:
  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: install semantic release replace plugin
        run: npm install @google/semantic-release-replace-plugin -D
      - name: install lodash
        run: npm install lodash -D
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_win_nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            win_docker:
              - 'ronmallory/win_nuget/*'
              - 'ronmallory/win_nuget/**/*'
              - 'ronmallory/win_nuget/**/**/*'

      - name: Build and Deploy Collection
        if: steps.filter.outputs.win_docker == 'true'
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          collection_dir: './ronmallory/win_nuget'
...
