---
# actions to run on pull_request to publish to ansible-galaxy

name: publish

on:
  push:
    branches:
      - master
jobs:

  publish_win_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          # inline YAML or path to separate file (e.g.: .github/filters.yaml)
          filters: |
            win_docker:
              - 'ronmallory/win_nuget/*'
              - 'ronmallory/win_nuget/**/*'
              - 'ronmallory/win_nuget/**/**/*'

      - name: Build and Deploy Collection
        if: steps.filter.outputs.win_docker == 'true'
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          collection_dir: './ronmallory/win_docker'
...
